
/**
 * @generated by openapi-mock-gen
 * If you want to make changes, please remove this entire comment and edit the file directly.
 */

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import { faker } from '@faker-js/faker';

faker.seed(123);

const mockData = () => ({
  200: {
    id: 123,
    name: 'John Doe',
    nested: Array.from({ length: 100 }, () => ({
      number: faker.number.int({ min: 0, max: 9999999, multipleOf: 1 }),
    })),
  },
});

export default mockData;