/**
 * @generated by openapi-mock-gen
 * If you want to make changes, please remove this entire comment and edit the file directly.
 */

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import { faker } from '@faker-js/faker';

faker.seed(123);

const mockData = () => ({
  200: {
    id: faker.string.uuid(),
    user_id: faker.string.uuid(),
    auth_token: faker.internet.jwt(),
    refresh_token: faker.internet.jwt(),
    created_at: faker.date.past(),
    updated_at: faker.date.past(),
    street_address: faker.location.streetAddress(),
    city_name: faker.location.city(),
    state_code: faker.location.state(),
    zip_code: faker.location.zipCode(),
    country_name: faker.location.country(),
    postal_code: faker.location.zipCode(),
    latitude_coord: faker.location.latitude(),
    longitude_coord: faker.location.longitude(),
    phone_number: faker.phone.number(),
    mobile_phone: faker.phone.number(),
    email_address: faker.internet.email(),
    username: faker.person.fullName(),
    redirect_url: faker.internet.url(),
    homepage_uri: faker.internet.url(),
    profile_photo: faker.image.avatar(),
    profile_image: faker.image.avatar(),
    profile_picture: faker.image.avatar(),
    avatar_img: faker.image.avatar(),
    banner_image: faker.image.urlLoremFlickr(),
    page_title: faker.lorem.sentence(),
    bio_description: faker.lorem.paragraph(),
    about_content: faker.lorem.paragraph(),
    intro_text: faker.lorem.paragraph(),
    bio_paragraph: faker.lorem.paragraph(),
    latest_comment: faker.lorem.sentence(),
  },
});

export default mockData;