/**
 * @generated by openapi-mock-gen
 * If you want to make changes, please remove this entire comment and edit the file directly.
 */

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import { faker } from '@faker-js/faker';

faker.seed(123);

const mockData = () => ({
  200: {
    shortString: faker.string.alpha({ length: { min: 3, max: 10 } }),
    exactLengthString: faker.string.alpha({ length: { min: 8, max: 8 } }),
    minOnlyString: faker.string.alpha({ length: { min: 5 } }),
    maxOnlyString: faker.string.alpha({ length: { max: 15 } }),
    phonePattern: faker.helpers.fromRegExp(/^\+?[1-9]\d{1,14}$/),
    alphanumericPattern: faker.helpers.fromRegExp(/^[a-zA-Z0-9]+$/),
    emailPattern: faker.helpers.fromRegExp(/^[\w\.-]+@[\w\.-]+\.[a-zA-Z]{2,}$/),
    uppercasePattern: faker.helpers.fromRegExp(/^[A-Z]{3,6}$/),
    numberPattern: faker.helpers.fromRegExp(/^\d{4}-\d{2}-\d{2}$/),
    hexColorPattern: faker.helpers.fromRegExp(/^#[0-9A-Fa-f]{6}$/),
    constrainedWithPattern: faker.helpers.fromRegExp(/^[a-z]+$/),
    complexPattern: faker.helpers.fromRegExp(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d@$!%*?&]{8,}$/),
  },
});

export default mockData;