/**
 * @generated by openapi-mock-gen
 * If you want to make changes, please remove this entire comment and edit the file directly.
 */

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

const mockData = () => ({
  200: {
    stringWithExample: 'This is an example string',
    numberWithExample: 42,
    booleanWithExample: true,
    enumWithExample: 'value2',
    objectWithExample: { name: 'John Doe', age: 30 },
    arrayWithExample: ['item1', 'item2', 'item3'],
    nestedObjectWithExamples: {
      parent: { child: 'parent level example', count: 10 },
    },
    arrayOfObjectsWithExamples: [
      { id: 1, status: 'active' },
      { id: 2, status: 'inactive' },
    ],
    complexExample: {
      metadata: { version: '1.0.0', tags: ['production', 'stable'] },
      data: { value: 'complex example data' },
    },
    nullExample: null,
    emptyStringExample: '',
    zeroNumberExample: 0,
    falseBooleanExample: false,
  },
});

export default mockData;