/**
 * @generated by openapi-mock-gen
 * If you want to make changes, please remove this entire comment and edit the file directly.
 */

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import { faker } from '@faker-js/faker';

faker.seed(123);

const mockData = () => ({
  200: {
    noOverride: faker.lorem.words(),
    overrideType: 'Overrided',
    overrideFormat: 'Overrided',
    overrideHeuristic_street: 'Overrided',
    overrideExample: 'Overrided',
    overrideWithFaker: (() => faker.number.int({ min: 1, max: 5, multipleOf: 1 }))(),
    overrideWithFakerString: faker.number.int({ min: 1, max: 5, multipleOf: 1 }),
    overrideWithFunction: (() => 'Overrided')(),
    overrideWithComplexFunction: (() => {
      const random = Math.random();
      return random > 0.5 ? 'Overrided' : 'Overrided Also';
    })(),
    overrideWithRegex: {
      user_age: 'Overrided',
      user_height: 'Overrided',
      get_user_name: 'Overrided',
      fallback_field: faker.lorem.words(),
    },
    arrayOfCustom: Array.from({ length: 1 }, () => ({
      overrideType: 'Overrided',
      fallback_field: faker.lorem.words(),
    })),
    nestedCustom: {
      fallback_field: faker.lorem.words(),
      inner: { get_user_name: 'Overrided' },
    },
  },
});

export default mockData;