/**
 * @generated by openapi-mock-gen
 * If you want to make changes, please remove this entire comment and edit the file directly.
 */

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import { faker } from '@faker-js/faker';

faker.seed(123);

const mockData = () => ({
  200: {
    email: faker.internet.email(),
    idnEmail: faker.internet.email(),
    website: faker.internet.url(),
    iri: faker.internet.url(),
    uriReference: faker.internet.url(),
    iriReference: faker.internet.url(),
    uriTemplate: faker.internet.url(),
    birthDate: faker.date.past().toISOString().substring(0, 10),
    birthDateTime: faker.date.past(),
    loginTime: new Date().toISOString().substring(11, 16),
    userId: faker.string.uuid(),
    hostname: faker.internet.domainName(),
    idnHostname: faker.internet.domainName(),
    ipv4: faker.internet.ip(),
    ipv6: faker.internet.ipv6(),
  },
});

export default mockData;