/**
 * @generated by openapi-mock-gen
 * If you want to make changes, please remove this entire comment and edit the file directly.
 */

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import { faker } from '@faker-js/faker';

faker.seed(123);

const mockData = () => ({
  200: {
    id: (() => Math.random().toString(36).substring(2, 15))(),
    username: faker.person.fullName(),
    email: faker.lorem.words(),
    role: (() => 'admin')(),
    arrayOfStrings: Array.from({ length: 1 }, () => faker.lorem.words()),
    nestedObject: {
      user_string: faker.person.fullName(),
      guest_object: { random: "Jane Doe" },
      user_array: Array.from({ length: 1 }, () => faker.lorem.words()),
      guest_array: faker.lorem.words(),
    },
  },
});

export default mockData; 