/**
 * @generated by openapi-mock-gen
 * If you want to make changes, please remove this entire comment and edit the file directly.
 */

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import { faker } from '@faker-js/faker';

faker.seed(123);

const mockData = () => ({
  200: {
    simpleObject: {
      name: faker.person.fullName(),
      value: faker.number.int({ min: 0, max: 9999999, multipleOf: 1 }),
    },
    emptyObject: {},
    objectWithAdditionalProperties: {
      fixedProperty: faker.lorem.words(),
      [faker.lorem.words()]: faker.lorem.words(),
    },
    objectWithTypedAdditionalProperties: {
      [faker.lorem.words()]: {
        id: faker.string.uuid(),
        timestamp: faker.date.past(),
      },
    },
    objectWithBooleanAdditionalProperties: {
      baseProperty: faker.lorem.words(),
      [faker.lorem.words()]: faker.lorem.words(),
    },
    objectWithNoAdditionalProperties: { strictProperty: faker.lorem.words() },
    nestedObjectStructure: {
      level1: { level2: { level3: { deepProperty: faker.lorem.words() } } },
    },
  },
});

export default mockData;